version: '3.8'

services:
  backend:
    image: arvindh01/docker-backend-taskify:latest
    container_name: backend-service
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - MONGO_URL=mongodb://mongo:27017/taskdb
    depends_on:
      - mongo
    networks:
      - mern_network

  frontend:
    image: arvindh01/docker-frontend-taskify:latest
    container_name: frontend-service
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - mern_network

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - mern_network

volumes:
  mongo_data:

networks:
  mern_network:
    driver: bridge
