apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: arvindh01/taskify-backend:latest  # Use your Docker Hub image
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_URI
              value: "mongodb://mongo-service:27017/taskdb"
            - name: CLIENT_URL
              value: "http://localhost:5173"
