apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
  namespace: taskify
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/uploads
